---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 3.2.0
serverless_language: ''
polling_url: 'https://api.airvisual.com/v2/nearest_city?lat={{ lat_lon | split: '','' | first }}&lon={{ lat_lon | split: '','' | last }}&key={{ api_key }}'
polling_headers: ''
polling_body: ''
id: 407459
oauth_enabled: 'false'
oauth_pkce_enabled: 'no'
oauth_authorize_url: ''
oauth_token_url: ''
oauth_scopes: ''
oauth_scope_separator: ''
oauth_refresh_url: ''
oauth_auth_params: ''
oauth_token_headers: ''
oauth_token_site: ''
oauth_token_params: ''
oauth_token_request_auth_method: ''
oauth_body_format: ''
oauth_token_response_metadata: ''
oauth_authorization_method: ''
oauth_refresh_params: ''
oauth_token_field_name: ''
oauth_expiry_field_name: ''
oauth_expiry_strategy: ''
oauth_fixed_expiry_ms: ''
custom_fields:
- keyname: api_key
  field_type: string
  name: API Key
  description: Find this at https://dashboard.iqair.com/personal/api-keys
- keyname: lat_lon
  field_type: lat_lon
  name: Location
  description: Search for a city or postal code, or provide a comma-separated lat/long.
- keyname: author_bio
  name: About This Plugin
  category: environment
  field_type: author_bio
  description: Air quality information from IQAir's Air Visual API. TRMNL Plugin by 2bithacker.
  github_url: https://github.com/2bithacker/trmnl-airvisual
  email_address: chip@2bithacker.net
name: AirVisual
description: US AQI information from IQAir
refresh_interval: 60
